version: 0.0
os: linux
files:
        - source: /
          destination: /home/ubuntu/codepipeline/python

hooks:
        BeforeInstall:
                - location: Scripts/install_dependencies.sh
                - location: Scripts/BeforeInstall.sh
                  timeout: 300
                  runas: root
        ApplicationInstall:
                - location: Scripts/AfterInstall.sh
                  timeout: 600
                  runas: root


