version: 0.2

phases:
  pre_build:
    commands:
      - echo 'Checking Python version...'
      - python3 --version
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code
      - python3 -m venv env
      - source env/bin/activate
      - pip install -r requirements.txt
artifacts:
  files:
    - '**/*'